# Azure Pipelines configuration
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

- script: |
    npm i
    npm run test
  displayName: 'Test by mocha'

